version: '3.3'
services:
  fishstore:
    image: mysql:9.1.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'fishstore'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: